# Data science(Introduction) avec la bibliothèque numpy

In [10]:
#importation de la bibliothèqe nmpy (convention standar)
import numpy as np

#création d'un tableau vectoriel (1 Dimension)
poids_kg=np.array([10,20,30,40,35])

print(f"Poids en kg : {poids_kg}")

# 2. Opération Vectorisée (sans boucle!)
# Conversion des KG en Livres (1 kg = 2.20462 lbs)
conversion_facteur = 2.20462
poids_lbs = poids_kg * conversion_facteur

print(f"Pois en lbs : {poids_lbs}")

# 3. Création d'un arraay 2d (matrice)
matrice_scores = np.array([
    [90, 85, 92], # Ligne 0
    [78, 88, 95], # Ligne 1
    [65, 72, 80]  # Ligne 2
])
print("\nMatrice des Scores (3 étudiants, 3 examens) :\n", matrice_scores)

# 4. Opération de Statistiques Rapides
# Calculer la moyenne des scores pour TOUS les examens
moyenne_globale = np.mean(matrice_scores)
print(f"Moyenne globale : {moyenne_globale:.2f}")

# Calculer la moyenne par examen (axe=0 pour les colonnes)
moyenne_par_examen = np.mean(matrice_scores, axis=0) 
print(f"Moyenne de chaque examen : {moyenne_par_examen}")


Poids en kg : [10 20 30 40 35]
Pois en lbs : [22.0462 44.0924 66.1386 88.1848 77.1617]

Matrice des Scores (3 étudiants, 3 examens) :
 [[90 85 92]
 [78 88 95]
 [65 72 80]]
Moyenne globale : 82.78
Moyenne de chaque examen : [77.66666667 81.66666667 89.        ]


In [12]:
score_par_etudiant=np.sum(matrice_scores,axis=1)
print(f"la somme des examens par etudiants :{score_par_etudiant}")

la somme des examens par etudiants :[267 261 217]


# Masqe Booléen

In [13]:
# 1. Créer le masque booléen
# Un masque est un tableau de True/False de la même forme que la matrice
masque_sup_85 = matrice_scores > 85 
print(f"Masque Booléen :\n{masque_sup_85}")

# 2. Appliquer le masque
# NumPy ne sélectionne que les éléments où le masque est True
scores_superieurs_85 = matrice_scores[masque_sup_85]

print(f"\nScores supérieurs à 85 : {scores_superieurs_85}")
# Output : [90 92 88 95]

Masque Booléen :
[[ True False  True]
 [False  True  True]
 [False False False]]

Scores supérieurs à 85 : [90 92 88 95]


In [16]:
# score inferieur 80
masque_inf_80=matrice_scores<80
print(f"Masque booléen : \n {masque_inf_80}")

score_inf_80=matrice_scores[masque_inf_80]
print(f"Les scores inférieurs à 80 : {score_inf_80}")

Masque booléen : 
 [[False False False]
 [ True False False]
 [ True  True False]]
Les scores inférieurs à 80 : [78 65 72]


# Introduction à la bibliothèqe Pandss

In [19]:
import pandas as pd
import numpy as np

# 1. Préparation des données sous forme de dictionnaire
data = {
    'Nom': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 22, 28],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Nice', 'Lyon'],
    # Utilisation d'un NaN (Not a Number) de NumPy pour une valeur manquante
    'Revenu': [50000, 65000, np.nan, 40000, 72000] 
}

df_clients=pd.DataFrame(data)

print("--- 5 premières lignes (df.head()) ---")
print(df_clients.head()) # Affiche les 5 premières lignes

print("\n--- Informations sur la structure (df.info()) ---")
df_clients.info() # Donne les types de données, les valeurs non nulles, et l'utilisation mémoire

print("\n--- Statistiques descriptives (df.describe()) ---")
print(df_clients.describe()) # Donne la moyenne, l'écart-type, les quartiles pour les colonnes numériques


--- 5 premières lignes (df.head()) ---
       Nom  Age  Ville   Revenu
0    Alice   25  Paris  50000.0
1      Bob   30   Lyon  65000.0
2  Charlie   35  Paris      NaN
3    David   22   Nice  40000.0
4      Eve   28   Lyon  72000.0

--- Informations sur la structure (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Nom     5 non-null      object 
 1   Age     5 non-null      int64  
 2   Ville   5 non-null      object 
 3   Revenu  4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

--- Statistiques descriptives (df.describe()) ---
             Age        Revenu
count   5.000000      4.000000
mean   28.000000  56750.000000
std     4.949747  14453.949864
min    22.000000  40000.000000
25%    25.000000  47500.000000
50%    28.000000  57500.000000
75%    30.000000  66750.000000
max    35.000000  72000.000000