# Data science(Introduction) avec la bibliothèque numpy

In [10]:
#importation de la bibliothèqe nmpy (convention standar)
import numpy as np

#création d'un tableau vectoriel (1 Dimension)
poids_kg=np.array([10,20,30,40,35])

print(f"Poids en kg : {poids_kg}")

# 2. Opération Vectorisée (sans boucle!)
# Conversion des KG en Livres (1 kg = 2.20462 lbs)
conversion_facteur = 2.20462
poids_lbs = poids_kg * conversion_facteur

print(f"Pois en lbs : {poids_lbs}")

# 3. Création d'un arraay 2d (matrice)
matrice_scores = np.array([
    [90, 85, 92], # Ligne 0
    [78, 88, 95], # Ligne 1
    [65, 72, 80]  # Ligne 2
])
print("\nMatrice des Scores (3 étudiants, 3 examens) :\n", matrice_scores)

# 4. Opération de Statistiques Rapides
# Calculer la moyenne des scores pour TOUS les examens
moyenne_globale = np.mean(matrice_scores)
print(f"Moyenne globale : {moyenne_globale:.2f}")

# Calculer la moyenne par examen (axe=0 pour les colonnes)
moyenne_par_examen = np.mean(matrice_scores, axis=0) 
print(f"Moyenne de chaque examen : {moyenne_par_examen}")


Poids en kg : [10 20 30 40 35]
Pois en lbs : [22.0462 44.0924 66.1386 88.1848 77.1617]

Matrice des Scores (3 étudiants, 3 examens) :
 [[90 85 92]
 [78 88 95]
 [65 72 80]]
Moyenne globale : 82.78
Moyenne de chaque examen : [77.66666667 81.66666667 89.        ]


In [12]:
score_par_etudiant=np.sum(matrice_scores,axis=1)
print(f"la somme des examens par etudiants :{score_par_etudiant}")

la somme des examens par etudiants :[267 261 217]


# Masqe Booléen

In [13]:
# 1. Créer le masque booléen
# Un masque est un tableau de True/False de la même forme que la matrice
masque_sup_85 = matrice_scores > 85 
print(f"Masque Booléen :\n{masque_sup_85}")

# 2. Appliquer le masque
# NumPy ne sélectionne que les éléments où le masque est True
scores_superieurs_85 = matrice_scores[masque_sup_85]

print(f"\nScores supérieurs à 85 : {scores_superieurs_85}")
# Output : [90 92 88 95]

Masque Booléen :
[[ True False  True]
 [False  True  True]
 [False False False]]

Scores supérieurs à 85 : [90 92 88 95]


In [16]:
# score inferieur 80
masque_inf_80=matrice_scores<80
print(f"Masque booléen : \n {masque_inf_80}")

score_inf_80=matrice_scores[masque_inf_80]
print(f"Les scores inférieurs à 80 : {score_inf_80}")

Masque booléen : 
 [[False False False]
 [ True False False]
 [ True  True False]]
Les scores inférieurs à 80 : [78 65 72]
