# Data science(Introduction) avec la bibliothèque numpy

In [6]:
#importation de la bibliothèqe nmpy (convention standar)
import numpy as np

#création d'un tableau vectoriel (1 Dimension)
poids_kg=np.array([10,20,30,40,35])

print(f"Poids en kg : {poids_kg}")

# 2. Opération Vectorisée (sans boucle!)
# Conversion des KG en Livres (1 kg = 2.20462 lbs)
conversion_facteur = 2.20462
poids_lbs = poids_kg * conversion_facteur

print(f"Pois en lbs : {poids_lbs}")

# 3. Création d'un arraay 2d (matrice)
matrice_scores = np.array([
    [90, 85, 92], # Ligne 0
    [78, 88, 95], # Ligne 1
    [65, 72, 80]  # Ligne 2
])
print("\nMatrice des Scores (3 étudiants, 3 examens) :\n", matrice_scores)


Poids en kg : [10 20 30 40 35]
Pois en lbs : [22.0462 44.0924 66.1386 88.1848 77.1617]

Matrice des Scores (3 étudiants, 3 examens) :
 [[90 85 92]
 [78 88 95]
 [65 72 80]]
